### ISSUE TITLE
t/opt-00.t fails on debian/buster

### ISSUE THREAD

**Issue by eserte** [petdance/html-tidy5#11]
On debian/buster (= current testing) the test suite fails:
```
# Testing HTML::Tidy5 1.04, tidy 5.6.0, Perl 5.028001, /usr/bin/perl
...
#   Failed test 'Cleaned stuff looks like what we expected'
#   at t/opt-00.t line 68.
#     Structures begin differing at:
#          $got->[9] = ' span.myprefix1 {color: blue}'
#     $expected->[9] = ' span.myprefix-1 {color: blue}'
# Looks like you failed 1 test of 1.
t/opt-00.t .................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

**Comment by petdance** [comment]
Thanks for the report.  I'm pretty sure this has been fixed but not yet released.  If you have a minute, would you be able to test this on the `dev` branch?

**Comment by eserte** [comment]
I tried 432f0681f70fe8bfc54ca8bf81d30d2c83ba968d, but still the same failure.

**Comment by eserte** [comment]
Here a Dockerfile to reproduce in a clean setup:
```
# maybe: docker pull debian:buster
# docker build -t perl-test . && docker run perl-test
FROM debian:buster
RUN apt-get -y update
RUN apt-get -y install perl-modules
RUN apt-get -y install make gcc
RUN apt-get -y install libtidy-dev git
WORKDIR /tmp
RUN git clone --depth=1 https://github.com/petdance/html-tidy5.git -b dev
WORKDIR /tmp/html-tidy5 
CMD cpan -t .
```

**Comment by shlomif** [comment]
@eserte @petdance : I wrote a fix for a similar failure for HTML-T5 on mageia v8 - https://github.com/shlomif/html-tidy5/commit/8a389829e6af192b9f612a28db1916a05d3e1477 - feel free to borrow it.

**Comment by greeneg** [comment]
Attached patch fixes this error

Based off @shlomif's patch

[opt-00.patch.txt](https://github.com/petdance/html-tidy5/files/4699521/opt-00.patch.txt)

**Comment by niceperl** [comment]
Is it safe to ignore that failing test?

**Comment by petdance** [comment]
Yeah, you can ignore it.
